[project]
name = "312-avoiding-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.2.0",
    "numpy>=2.4.2",
    "seaborn>=0.13.2",
    "torch>=2.10.0",
]
